# Generated by Django 2.2.5 on 2019-10-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.BooleanField(default=True, verbose_name='Activar / Desactivar')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del area')),
                ('jefe', models.CharField(default='N/A', max_length=200, verbose_name='Nombre del jefe de area')),
                ('imagen_referencial', models.ImageField(blank=True, null=True, upload_to='AreasTrabajo/', verbose_name='Imagen referencial')),
            ],
            options={
                'verbose_name': 'Area de trabajo',
                'verbose_name_plural': 'Areas de trabajo',
            },
        ),
    ]
