# Generated by Django 2.2.5 on 2019-10-10 17:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Puestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.BooleanField(default=True, verbose_name='Activar / Desactivar')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del candidato')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo electrónico')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='Candidatos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Curriculum')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Puestos.Puestos')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
    ]
