# Generated by Django 2.2.5 on 2019-10-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='Candidatos/', verbose_name='Curriculum'),
        ),
    ]
