# Generated by Django 2.2.5 on 2019-10-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.BooleanField(default=True, verbose_name='Activar / Desactivar')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del puesto')),
                ('direccion', models.CharField(max_length=200, null=True, verbose_name='Dirección')),
                ('salario', models.CharField(max_length=200, verbose_name='Salario (Mensual)')),
                ('jornada', models.CharField(max_length=200, verbose_name='Jornada')),
                ('contrato', models.CharField(max_length=200, verbose_name='Contrato')),
                ('fecha_nacimiento', models.DateField(max_length=200, null=True, verbose_name='Fecha de nacimiento')),
                ('puesto', models.CharField(default='n/a', max_length=6, verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
