# Generated by Django 2.2.5 on 2019-10-09 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AreasTrabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.BooleanField(default=True, verbose_name='Activar / Desactivar')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('imss', models.CharField(max_length=11, verbose_name='Número de seguro social')),
                ('nivel_estudios', models.CharField(choices=[('pri', 'Primaria'), ('sec', 'Secundaria'), ('bac', 'Bachillerato'), ('lic', 'Licenciatura'), ('ing', 'Ingeniería '), ('mae', 'Maestría'), ('doc', 'Doctorado')], max_length=15, verbose_name='Nivel de estudios')),
                ('carrera', models.CharField(blank=True, max_length=50, null=True, verbose_name='Carrera Estudiada')),
                ('direccion', models.CharField(max_length=100, null=True, verbose_name='Dirección')),
                ('salario', models.CharField(max_length=200, verbose_name='Salario (Mensual)')),
                ('jornada', models.CharField(max_length=100, verbose_name='Jornada')),
                ('contrato', models.CharField(max_length=100, verbose_name='Contrato')),
                ('fecha_nacimiento', models.DateField(max_length=100, null=True, verbose_name='Fecha de nacimiento')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AreasTrabajo.AreasTrabajo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
