# Generated by Django 2.2.5 on 2019-10-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Salario (Mensual)'),
        ),
    ]
