# Generated by Django 2.2.5 on 2019-10-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_auto_20191004_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del empleado'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='puesto',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend')], default='n/a', max_length=6, verbose_name='Puesto'),
        ),
    ]
