# Generated by Django 2.2.5 on 2019-10-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0003_auto_20191007_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='puesto',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('iOs', 'iOs')], default='n/a', max_length=20, verbose_name='Puesto'),
        ),
    ]
