# Generated by Django 2.2.5 on 2019-10-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0005_auto_20191022_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
