# Generated by Django 2.2.5 on 2019-10-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0005_auto_20191007_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='puesto',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('iOs', 'iOs'), ('Android', 'Android')], default='n/a', max_length=20, verbose_name='Puesto'),
        ),
    ]
