# Generated by Django 2.2.5 on 2019-10-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0006_auto_20191028_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
