# Generated by Django 2.2.5 on 2019-11-06 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0007_auto_20191028_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
