# Generated by Django 2.2.5 on 2019-10-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0009_auto_20191007_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='puesto',
            field=models.OneToOneField(max_length=6, on_delete=django.db.models.deletion.CASCADE, to='AreasTrabajo.AreasTrabajo'),
        ),
    ]
