# Generated by Django 2.2.5 on 2019-10-09 01:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.BooleanField(default=True, verbose_name='Activar / Desactivar')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('disponible', models.BooleanField(default=False, verbose_name='Disponible')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del puesto')),
                ('salario', models.CharField(max_length=200, verbose_name='Salario')),
                ('jornada', models.CharField(max_length=200, verbose_name='Jornada')),
                ('contrato', models.CharField(max_length=200, verbose_name='Contrato')),
                ('imagen_referencial', models.ImageField(blank=True, null=True, upload_to='Puestos/', verbose_name='Imagen referencial')),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('requisitos', ckeditor.fields.RichTextField()),
                ('deseable', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
    ]
