# Generated by Django 2.2.5 on 2019-10-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Puestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestos',
            name='disponible',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
    ]
