# Generated by Django 2.2.5 on 2019-10-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Puestos', '0002_auto_20191004_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puestos',
            name='funciones',
        ),
    ]
