# Generated by Django 2.2.5 on 2019-09-26 17:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.BooleanField(default=True, verbose_name='Activar / Desactivar')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('nosotros', ckeditor.fields.RichTextField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram')),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkedin')),
                ('pagina', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pagina oficial')),
            ],
            options={
                'verbose_name': 'Datos de la empresa',
                'verbose_name_plural': 'Datos de la empresa',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.BooleanField(default=True, verbose_name='Activar / Desactivar')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del puesto')),
                ('direccion', models.CharField(max_length=200, null=True, verbose_name='Dirección')),
                ('salario', models.CharField(max_length=200, verbose_name='Salario (Mensual)')),
                ('jornada', models.CharField(max_length=200, verbose_name='Jornada')),
                ('contrato', models.CharField(max_length=200, verbose_name='Contrato')),
                ('fecha_nacimiento', models.DateField(max_length=200, null=True, verbose_name='Fecha de nacimiento')),
                ('puesto', models.CharField(choices=[('n/a', 'No asignado'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('ios', 'iOS'), ('android', 'Android'), ('rh', 'Recursos Humanos'), ('fundador', 'Fundador')], default='n/a', max_length=6, verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.BooleanField(default=True, verbose_name='Activar / Desactivar')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del puesto')),
                ('salario', models.CharField(max_length=200, verbose_name='Salario')),
                ('jornada', models.CharField(max_length=200, verbose_name='Jornada')),
                ('contrato', models.CharField(max_length=200, verbose_name='Contrato')),
                ('imagen_referencial', models.ImageField(blank=True, null=True, upload_to='Puestos/', verbose_name='Imagen referencial')),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('requisitos', ckeditor.fields.RichTextField()),
                ('deseable', ckeditor.fields.RichTextField()),
                ('funciones', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
    ]
