# Generated by Django 2.2.5 on 2019-10-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempresa',
            name='rfc',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='datosempresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='datosempresa',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='datosempresa',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
