# Generated by Django 2.2.5 on 2019-09-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='puesto',
            field=models.CharField(choices=[('Líder de Pruebas de QA', 'Líder de Pruebas de QA'), ('Desarrollador/a en Sistemas Web Java 1 año de experiencia programando Java', 'Desarrollador/a en Sistemas Web Java 1 año de experiencia programando Java')], default='n/a', max_length=6, verbose_name='Puesto'),
        ),
    ]
