# Generated by Django 2.2.5 on 2019-10-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20191013_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosempresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
    ]
