# Generated by Django 2.2.5 on 2019-09-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_areastrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='areastrabajo',
            name='imagen_referencial',
            field=models.ImageField(blank=True, null=True, upload_to='AreasTrabajo/', verbose_name='Imagen referencial'),
        ),
    ]
