# Generated by Django 2.2.5 on 2019-10-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_auto_20191017_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempresa',
            name='horario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Horario'),
        ),
    ]
