# Generated by Django 2.2.5 on 2019-09-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_areastrabajo_imagen_referencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areastrabajo',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del area'),
        ),
    ]
