# Generated by Django 2.2.5 on 2019-09-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_auto_20190927_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='puesto',
            field=models.CharField(choices=[('Android', 'Android')], default='n/a', max_length=6, verbose_name='Puesto'),
        ),
    ]
