# Generated by Django 2.2.5 on 2019-09-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_auto_20190927_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='areastrabajo',
            name='jefe',
            field=models.CharField(default='N/A', max_length=200, verbose_name='Nombre del jefe de area'),
        ),
    ]
